param(
    [string]$DistPath = "..\frontend\dist",
    [string]$OutputFile = "src\frontend-assets.ts"
)

$distDir = (Resolve-Path $DistPath).Path
$outputPath = Join-Path $PSScriptRoot "..\$OutputFile"

Write-Host "Reading files from $distDir"
Write-Host "Writing to $outputPath"

$rawHtml = [System.IO.File]::ReadAllText("$distDir\index.html")
# Insert diagnostic script before the module script; remove crossorigin from all tags
$diagScript = '<script>window.__diag="loading";window.onerror=function(m,s,l,c,err){window.__diag="err:"+m;document.title="ERR:"+m;var d=document.getElementById("root");if(d)d.innerHTML="<pre style=color:red;padding:2rem;background:#fff>"+m+"\\n"+(err&&err.stack||s+":"+l)+"</pre>"};window.addEventListener("error",function(e){window.__diag="err:"+e.message;document.title="ERR:"+e.message;console.error(e)});window.addEventListener("unhandledrejection",function(e){window.__diag="promise:"+e.reason;document.title="PROMISE:"+e.reason;console.error(e.reason)});</script>'
$indexHtml = $rawHtml -replace ' crossorigin', ''
$indexHtml = $indexHtml -replace '<script[^>]*?type="module"[^>]*?src="([^"]*)"[^>]*?>', "$diagScript<script type=`"module`" src=`"`$1`">"

# Walk entire dist directory recursively (handle binary files as base64)
$allFiles = Get-ChildItem "$distDir" -File -Recurse | Where-Object {
    $_.FullName -notlike "*\index.html" -and $_.Name -ne '_redirects'
}

function Get-ContentType($filename) {
    switch -Wildcard ($filename) {
        '*.js'    { return 'application/javascript' }
        '*.css'   { return 'text/css' }
        '*.svg'   { return 'image/svg+xml' }
        '*.png'   { return 'image/png' }
        '*.ico'   { return 'image/x-icon' }
        '*.webp'  { return 'image/webp' }
        '*.json'  { return 'application/json' }
        '*.glb'   { return 'model/gltf-binary' }
        '*.wasm'  { return 'application/wasm' }
        '*.jsm'   { return 'application/javascript' }
        default   { return 'application/octet-stream' }
    }
}

function Is-Binary($filename) {
    switch -Wildcard ($filename) {
        '*.glb'  { return $true }
        '*.wasm' { return $true }
        default  { return $false }
    }
}

function Get-PublicPath($fullPath, $distDir) {
    $relative = $fullPath.Substring($distDir.Length + 1) -replace '\\', '/'
    return "/$relative"
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// Auto-generated by scripts/generate-frontend-assets.ps1")
[void]$sb.AppendLine("// Do not edit manually.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("export interface StaticAsset {")
[void]$sb.AppendLine("  path: string;")
[void]$sb.AppendLine("  content: string;")
[void]$sb.AppendLine("  contentType: string;")
[void]$sb.AppendLine("  isBase64?: boolean;")
[void]$sb.AppendLine("}")
[void]$sb.AppendLine("")

# Index HTML
$escapedJson = ConvertTo-Json $indexHtml -Compress
[void]$sb.AppendLine("export const INDEX_HTML: string = $escapedJson;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("export const STATIC_ASSETS: StaticAsset[] = [")

foreach ($file in $allFiles) {
    $filename = Split-Path $file -Leaf
    $path = Get-PublicPath $file.FullName $distDir
    $escapedPath = ConvertTo-Json $path -Compress
    $contentType = Get-ContentType $filename
    [void]$sb.Append("  { path: $escapedPath, contentType: `"$contentType`"")

    if (Is-Binary $filename) {
        $bytes = [System.IO.File]::ReadAllBytes($file.FullName)
        $b64 = [System.Convert]::ToBase64String($bytes)
        $escapedB64 = ConvertTo-Json $b64 -Compress
        [void]$sb.Append(", content: $escapedB64, isBase64: true")
    } else {
        $content = [System.IO.File]::ReadAllText($file.FullName)
        $escapedContent = ConvertTo-Json $content -Compress
        [void]$sb.Append(", content: $escapedContent")
    }

    [void]$sb.AppendLine(" },")
}

[void]$sb.AppendLine("];")

[System.IO.File]::WriteAllText($outputPath, $sb.ToString())

Write-Host "Done. Generated $($allFiles.Count) static assets + index.html"
